### ISSUE TITLE
CSS overly repetitive

### ISSUE THREAD

**Issue by farishkash** [majicsal/prj-rev-bwfs-dasmoto#3]
One of the purposes of css is through the use of element selectors and class, is the reduce the number of times you write a style.

For example in your css you use font family repeatedly.  Since the whole page uses font-family Helvetica you can use an element selector like body to cover the whole page.

```
body{
  font-family:Helvetica;
}
```

Now you can remove font family from all your other html.

Another issue of repetition is that you wrote this multiple times for the h2 headings.

```
font-size:32px;
  font-weight:bold;
  color:white;
```
Just like with body you can use a h2 selector to use this once

```
h2{
font-size:32px;
  font-weight:bold;
  color:white;
}
```
Then for green, red, and blue classes the only thing you need to list is background color.

```
.green{
  background-color: mediumspringgreen;
}
.red{
  background-color:lightcoral;
}
.blue{
  background-color:skyblue;
}
```

**Comment by majicsal** [comment]
Ok i understand thanks very much.
